[package]
name = "apt_casino"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }

[addresses]
apt_casino = "0x421055ba162a1f697532e79ea9a6852422d311f0993eb880c75110218d7f52c0"